### PR TITLE
Updated to build with Node 4.2.2

### PR DESCRIPTION
**Pull request by fomojola**
Building on Node v4.2.2 on Ubuntu 14.04, repeated errors of the form

<code>
make: Entering directory `/var/local/textibility.api/node_modules/node-ipaddr/build'
  CXX(target) Release/obj.target/ippool/src/module.o
  CXX(target) Release/obj.target/ippool/src/ippool.o
../src/ippool.cc: In static member function ‘static int Ippool::GetAddr(v8::Handlev8::String, Ippool::GenericRange&, int)’:
../src/ippool.cc:282:41: error: call of overloaded ‘GetAddr(char_, Ippool::GenericRange&, int&)’ is ambiguous
  return(Ippool::GetAddr(_ip, gr, version));
                                         ^
../src/ippool.cc:282:41: note: candidates are:
../src/ippool.cc:280:5: note: static int Ippool::GetAddr(v8::Handlev8::String, Ippool::GenericRange&, int)
 int Ippool::GetAddr(Handle<String> str, Ippool::GenericRange &gr, int version) {
     ^
In file included from ../src/module.hh:37:0,
                 from ../src/ippool.cc:22:
../src/ippool.hh:58:14: note: static int Ippool::GetAddr(const string&, Ippool::GenericRange&, int)
   static int GetAddr(const std::string &str, GenericRange &gr, int version = 0);
              ^
../src/ippool.cc: In member function ‘bool Ippool::StoreIpAddr(v8::Handlev8::String, int)’:
../src/ippool.cc:372:39: error: call of overloaded ‘StoreIpAddr(char_, int&)’ is ambiguous
  return(this->StoreIpAddr(_ip, version));
                                       ^
../src/ippool.cc:372:39: note: candidates are:
../src/ippool.cc:370:6: note: bool Ippool::StoreIpAddr(v8::Handlev8::String, int)
 bool Ippool::StoreIpAddr(Handle<String> str, int version) {
      ^
In file included from ../src/module.hh:37:0,
                 from ../src/ippool.cc:22:
../src/ippool.hh:60:8: note: bool Ippool::StoreIpAddr(const string&, int)
   bool StoreIpAddr(const std::string &str, int version = 0);
        ^
../src/ippool.cc: In static member function ‘static int Ippool::GetAddr(v8::Handlev8::String, Ippool::GenericRange&, int)’:
../src/ippool.cc:283:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/ippool.cc: In member function ‘bool Ippool::StoreIpAddr(v8::Handlev8::String, int)’:
../src/ippool.cc:373:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: **\* [Release/obj.target/ippool/src/ippool.o] Error 1
</code>

are happening. I did a trivial rename of a number of functions to work around this, and now it build correctly.

### CODE REVIEW

**Comment by Dagrut** [comment]
Thank you!
